[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --speed 10000 --always-print-stacktrace --chip nRF52833_xxAA"
# rustflags = [
#   "-C", "linker=flip-link",
#   "-C", "link-arg=-Tlink.x",
#   "-C", "link-arg=-Tdefmt.x",
#   "-C", "link-arg=--nmagic",
# ]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[alias]
rrb = "run --release --bin"
brb = "build --release --bin"
test-lib = "test --target x86_64-unknown-linux-gnu"
